name = "zapdo"
compatibility_date = "2026-01-13"
compatibility_flags = ["nodejs_als"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
GOOGLE_CLIENT_ID = ""
GOOGLE_CALLBACK_URL = ""
GOOGLE_CLIENT_SECRET = ""

[env.production]
name = "zapdo"
[[env.production.routes]]
pattern = "zapdo.onichandame.com"
custom_domain = true

#[[env.production.d1_databases]]
#binding = "DB"
#database_name = "zapdo-db"
#database_id = "4bac8877-5a26-45f2-8a41-2c96c6b3a0a0"
#migrations_dir = "migrations"
#
#[[env.production.r2_buckets]]
#binding = "R2"
#bucket_name = "zapdo"
#
#[[env.production.kv_namespaces]]
#binding = "KV"
#id = "40eb4de4d58c496783264a9a953cc8b8"

[env.development]
name = "zapdo-dev"
[[env.development.routes]]
pattern = "zapdo-dev.onichandame.com"
custom_domain = true

[[env.development.d1_databases]]
binding = "DB"
database_name = "zapdo-db-dev"
database_id = "cd000fb7-5924-4205-b1a0-1cc427fbb47b"
migrations_dir = ".drizzle"

#[[env.development.r2_buckets]]
#binding = "R2"
#bucket_name = "zapdo-dev"
#
#[[env.development.kv_namespaces]]
#binding = "KV"
#id = "27b09115ef66447abb0437bd4d7d5389"
